name: Build, Push, and Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Who am I
      run: gcloud auth list

    - name: Authenticate Docker with Artifact Registry
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev


     ## === deploy FastAPI API ===
    - name: Build Docker image
      run: |
        docker build -f dockerfiles/fastapi_app.dockerfile \
          -t us-central1-docker.pkg.dev/fake-news-api-project/fastapi-repo/fastapi-api .

    - name: Push Docker image to Artifact Registry
      run: |
        docker push us-central1-docker.pkg.dev/fake-news-api-project/fastapi-repo/fastapi-api

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy fastapi-service \
          --image=us-central1-docker.pkg.dev/fake-news-api-project/fastapi-repo/fastapi-api \
          --platform=managed \
          --region=us-central1 \
          --allow-unauthenticated
