name: Train Model on Vertex AI

on:
  workflow_dispatch:

jobs:
  vertex-train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Configure Docker to use Artifact Registry
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build training Docker image
      run: |
        docker build -f dockerfiles/train_model.dockerfile \
          -t us-central1-docker.pkg.dev/fake-news-api-project/trainer-repo/train-job .

    - name: Push training image to Artifact Registry
      run: |
        docker push us-central1-docker.pkg.dev/fake-news-api-project/trainer-repo/train-job

    - name: Submit Vertex AI Custom Job
      run: |
        gcloud ai custom-jobs create \
          --region=us-central1 \
          --display-name=vertex-lstm-train \
          --worker-pool-spec=machine-type=n1-standard-4,replica-count=1,container-image-uri=us-central1-docker.pkg.dev/fake-news-api-project/trainer-repo/train-job
